[pt_table]
#partition table is 4K in size
address0 = 0xE000
address1 = 0xF000

[[pt_entry]]
type = 0
name = "FW"
device = 0
address0 = 0x10000
size0 = 0x111000
address1 = 0x121000
size1 = 0x87000
# compressed image must set len,normal image can left it to 0
len = 0

[[pt_entry]]
type = 2
name = "hfinfo"
device = 0
address0 = 0x1A8000
size0 = 0x19000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0

len = 0
[[pt_entry]]
type = 3
name = "factory"
device = 0
address0 = 0x1C1000
size0 = 0x8000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0

[[pt_entry]]
type = 4
name = "mfg"
device = 0
address0 = 0x1C9000
size0 = 0x30000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0

[[pt_entry]]
type = 5
name = "hfkv"
device = 0
address0 = 0x1F9000
size0 = 0x2000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0

[[pt_entry]]
type = 6
name = "PARAM1"
device = 0
address0 = 0x1FB000
size0 = 0x1000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0

[[pt_entry]]
type = 7
name = "PARAM2"
device = 0
address0 = 0x1FC000
size0 = 0x2000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0

[[pt_entry]]
type = 8
name = "PARAM3"
device = 0
address0 = 0x1FE000
size0 = 0x1000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0

[[pt_entry]]
type = 9
name = "PARAM4"
device = 0
address0 = 0x1FF000
size0 = 0x1000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0

[[pt_entry]]
type = 10
name = "media"
device = 0
address0 = 0x200000
size0 = 0
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0